controle_gado/controle_gado/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core_module')),
    path('admin/', admin.site.urls),
]

controle_gado/core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('login', login_empresa, name='login'),
    path('logout', logout_empresa, name='logout'),
    path('cadastro', cadastro_empresa, name='cadastro'),
    path('anonimo', consulta_anonima, name='anonimo'),
    path('acessocnpj', consulta_cnpj, name='acessocnpj'),
    path('gadocontrole', gado_controle, name='gadocontrole'),
    path('gadoupdate/<int:id>', gado_update, name='gadoupdate'),
    path('gadodelete/<int:id>', gado_delete, name='gadodelete'),
    path('gadosave', gado_save, name='gadosave'),

]

controle_gado/core/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
# modelo de entidade para a fazenda, algo simples que represente o acesso
# e o relacionamento com os especimes seu rebanho


class Gado(models.Model):
    peso = models.FloatField()
    data_cad = models.DateTimeField(auto_now_add=True)
    brinco_id = models.CharField(max_length=100)
    fazenda = models.ForeignKey('User_fazenda', on_delete=models.CASCADE, default=None, null=True)


class User_fazenda(User):
    nome_empresa = models.CharField(max_length=100)
    token = models.CharField(max_length=500)
    cnpj = models.IntegerField(null=True)

controle_gado/core/forms.py
# -*- coding: utf-8 -*-
from core.models import User_fazenda, Gado
from django.forms import ModelForm
from django.forms.widgets import *

import jwt


class FormFazenda(ModelForm):
    class Meta:
        model = User_fazenda
        fields = ['nome_empresa', 'username', 'password', 'token', 'cnpj']
        widgets = {
            'nome_empresa': TextInput(attrs={'placeholder': 'Employee', 'class': 'form-control'}),
            'username': TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}),
            'password': PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}),
            'token': TextInput(attrs={'placeholder': 'Token', 'class': 'form-control', 'value': 'none'}),
            'cnpj': NumberInput(attrs={'placeholder': 'Type your cnpj', 'class': 'form-control'})
        }

    def save(self, commit=True):
        fazenda = super(FormFazenda, self).save(commit=False)
        fazenda.set_password(self.cleaned_data['password'])
        fazenda.username = self.cleaned_data['username']

        payload = {
            'username': fazenda.username,
        }
        fazenda.token = jwt.encode(payload, 'jetbov', algorithm='HS256')
        if commit:
            fazenda.save()
        return fazenda


class GadoForm(ModelForm):
    class Meta:
        model = Gado
        fields = '__all__'
        widgets = {
            'peso': NumberInput(attrs={'class': 'form-control'}),
            'brinco_id': NumberInput(attrs={'class': 'form-control'}),
        }

controle_gado/core/views.py
from django.shortcuts import render, HttpResponse, redirect
from core.forms import FormFazenda, GadoForm
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.decorators import login_required
from core.models import *

import jwt


def index(request):
    formulario = FormFazenda
    return render(request, 'core/index.html', {'form': formulario})


def login_empresa(request):
    logout(request)
    form = FormFazenda(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        fazenda = authenticate(request, username=username, password=password)
        if fazenda is not None:
            login(request, fazenda)
            return redirect('/gadocontrole')
        else:
            return HttpResponse('Usuario nao cadastrado')
    return render(request, 'core/login.html', {'form': form})


def logout_empresa(request):
    logout(request)
    return redirect('/')


def cadastro_empresa(request):
    form = FormFazenda(request.POST or None)
    if request.method == 'POST':
        form.save()
        return redirect('/login')
    return render(request, 'core/cadastro.html', {'form': form})


def consulta_cnpj(request):
    if request.method == 'POST':
        fazenda = User_fazenda.objects.get(cnpj=request.POST.get('cnpj'))
        rebanho = Gado.objects.filter(fazenda_id=fazenda.id)
        return render(request, 'core/listagem_animais.html', {'rebanho': rebanho})
    return render(request, 'core/acesso_cnpj.html')


def consulta_anonima(request):
    if request.method == 'POST':
        user = jwt.decode(request.POST.get('token'), 'jetbov', algorithms=['HS256'])
        fazenda = User_fazenda.objects.get(username=user['username'])
        rebanho = Gado.objects.filter(fazenda_id=fazenda.id, brinco_id=request.POST.get('brinco_id'))
        return render(request, 'core/listagem_animais.html', {'rebanho': rebanho})

    return render(request, 'core/acesso_anonimo.html')


@login_required
def gado_controle(request):
    user = get_user(request)
    rebanho = Gado.objects.filter(fazenda_id=user.id)
    templatevars = {
        'form': GadoForm(),
        'rebanho': rebanho,
        'fazenda': User_fazenda.objects.get(username=user.username),
    }
    return render(request, 'core/gado_controle.html', templatevars)


@login_required
def gado_save(request):
    if request.method == 'POST':
        gado = Gado()
        gado.peso = request.POST.get('peso')
        gado.brinco_id = request.POST.get('brinco_id')
        gado.fazenda = User_fazenda.objects.get(username=get_user(request).username)
        gado.save()
        return redirect('/gadocontrole')
    return redirect('/gadocontrole')


@login_required
def gado_update(request, id):
    gadoitem = Gado.objects.get(id=id)
    gadoitem.peso = request.POST.get('peso')
    gadoitem.brinco_id = request.POST.get('brinco_id')
    gadoitem.save()
    return redirect('/gadocontrole')


@login_required
def gado_delete(request, id):
    gadoitem = Gado.objects.get(id=id)
    gadoitem.delete()
    return redirect('/gadocontrole')

controle_gado/controle_gado/templates/core/acesso_anonimo.html
{% extends 'core/base.html' %}
{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1>Insira seus dados:</h1>
        <form class="form-group" action="/anonimo" method="POST">
            {% csrf_token %}
            <div class="row">
                    <label class="col-md-10">Token para acesso anônimo:</label>
                    <div class="input-group col-md-10">
                        <span class="input-group-addon">
                            <i class="fa fa-key"></i>
                        </span>
                        <input type="text" name="token" class="form-control">
                    </div>
                </div>
            <div class="row">
                <label class="col-md-10">Brinco do animal:</label>
                <div class="input-group col-lg-6">
                    <span class="input-group-addon">
                        <i class="fa fa-asterisk"></i>
                    </span>
                    <input type="number" name="brinco_id" class="form-control">
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-user-plus"></i>
                Verificar</button>
        </form>
    </div>
</div>

{% endblock %}

controle_gado/controle_gado/templates/core/acesso_cnpj.html
{% extends 'core/base.html' %}
{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1>Insira seus dados:</h1>
        <form class="form-group" action="/acessocnpj" method="POST">
            {% csrf_token %}
            <div class="row">
                <label class="col-md-10">CNPJ para listagem:</label>
                <div class="input-group col-lg-6">
                    <span class="input-group-addon">
                        <i class="fa fa-briefcase"></i>
                    </span>
                    <input type="number" name="cnpj" class="form-control">
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-user-plus"></i>
                Verificar</button>
        </form>
    </div>
</div>

{% endblock %}

controle_gado/controle_gado/templates/core/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="por">
<head>
    <meta charset="UTF-8">
    <title>Controle JetBov</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'core/css/core.css' %}">
</head>
<body>
<nav class="navbar navbar-expand bg-dark navbar-dark" id="navegation-bar">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link navbar-brand" href="/">
                JetBov
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'core:login' %}">Entrar</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cadastro' %}">Cadastrar-se</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'core:anonimo' %}">
                <i class="fa fa-eye-slash"></i>
                Anônimo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'core:acessocnpj' %}">Via CNPJ</a>
        </li>

    </ul>

</nav>

    {% block body %}
    {% endblock %}

<script src="{% static 'core/js/bootstrap.min.js' %}"></script>
</body>


</html>

controle_gado/controle_gado/templates/core/cadastro.html
{% extends 'core/base.html' %}

{% block body %}
{% load staticfiles %}
    <div class="jumbotron" id="container_cadastro">
            <h1>Cadastro</h1>
        <div class="container row">
            <form class="form-group col-md-6" action="/cadastro" method="POST">
                {% csrf_token %}
                <div class="row">
                    <label class="col-md-10">Empresa:</label>
                    <div class="input-group col-md-10">
                        <span class="input-group-addon">
                            <i class="fa fa-black-tie"></i>
                        </span>
                            {{ form.nome_empresa }}
                    </div>
                </div>
                <div class="row">
                    <label class="col-md-10">Cnpj:</label>
                    <div class="input-group col-md-10">
                        <span class="input-group-addon"><i class="fa fa-briefcase"></i></span>
                            {{ form.cnpj }}
                    </div>
                </div>
                <div class="row">
                    <label class="col-md-10">Nome de usuario:</label>
                    <div class="input-group col-md-10">
                        <span class="input-group-addon">@</span>
                        {{ form.username }}
                    </div>
                </div>

                <div class="row">
                    <label class="col-md-10">Senha de acesso:</label>
                    <div class="input-group col-md-10">
                        <span class="input-group-addon">
                            <i class="fa fa-asterisk"></i>
                        </span>
                        {{ form.password }}
                    </div>
                </div>

                <div class="row">
                    <label class="col-md-10">Confirme sua senha:</label>
                    <div class="input-group col-md-10">
                        <span class="input-group-addon">
                            <i class="fa fa-asterisk"></i>
                        </span>
                        <input oninput="validacaoSenha(this)" required class="form-control" type="password" name="confirm_password" placeholder="Rewrite your password" id="id_confirm_password">
                    </div>
                </div>
                <br>
                <div hidden>
                    {{ form.token }}
                </div>
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-user-plus"></i>
                    Cadastro</button>
            </form>
            <div class="col-md-6">

            <img src="{% static 'core/imgs/texas-gado.png' %}" style="width:100%;">
            </div>
        </div>
    </div>
<script src="{% static 'core/js/core.js' %}"></script>
{% endblock %}

controle_gado/controle_gado/templates/core/gado_controle.html
{% extends 'core/base.html' %}
{% block body %}

{% load staticfiles %}
    <div class="jumbotron">
        <div class="container">
        <br>
        <form class="form-group row" action="/gadosave" method="POST">
            {% csrf_token %}
                <h2>Controle do rebanho - {{ fazenda.nome_empresa }}:</h2>

                <div class="container">
                        <a class="btn btn-default">token: </a>

                        {{ fazenda.token }}
                    </div>
                <br>
                <div class="input-group col-mg-6">
                        <span class="input-group-addon col-mg-6">Peso</span>
                        {{ form.peso }}
                    </div>
                <div class="input-group col-mg-6">
                        <span class="input-group-addon">Brinco</span>
                        {{ form.brinco_id }}
                    </div>
                <button class="btn btn-success" type="submit">Cadastrar</button>
            </form>
    </div>
    </div>
    <div class="container">
        <div class="container">
                <ul class="list-group">

                    <h5>Quantidade de animais cadastrados: {{ rebanho.count }}</h5>
                    {% for gado in rebanho %}
                    <li class="list-group-item">
                        <form id="form_gadolistagem" action="" method="POST">
                            {% csrf_token %}
                            <div class="input-group">
                                <span class="input-group-addon">Peso:</span>
                                <input class="input-group-item" type="number" value="{{ gado.peso }}" name="peso">
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon">Brinco:</span>
                                <input class="input-group-item" type="number" value="{{ gado.brinco_id }}" pattern="[0-9]+$" name="brinco_id">
                            </div>
                            <button class="btn btn-primary" type="submit" onclick="ChangeAction('/gadoupdate/{{ gado.id }}');">Alterar</button>
                            <button class="btn btn-warning" type="submit" onclick="ChangeAction('/gadodelete/{{ gado.id }}');">Deletar</button>

                        </form>
                    </li>
                    {% endfor %}
                </ul>
        </div>
    </div>
<script src="{% static 'core/js/core.js' %}"></script>
{% endblock %}

controle_gado/controle_gado/templates/core/index.html
{% extends 'core/base.html' %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1>Bem vindo, controle sua fazenda</h1>
        <h4>comece a ter o controle do seu rebanho.</h4>
        <div class="container"></div>
            <a class="btn btn-success btn-lg" href="{% url 'core_module:login' %}">Login</a>
            <a class="btn btn-primary btn-lg" href="{% url 'core_module:cadastro' %}">Cadastre-se</a>
        </div>
</div>
{% endblock %}

controle_gado/controle_gado/templates/core/listagem_animais.html
{% extends 'core/base.html' %}
{% block body %}

    <div class="container">
        <div class="container">
                <ul class="list-group">
                    <h5>Quantidade da listagem: {{ rebanho.count }}</h5>
                    {% for gado in rebanho %}
                    <li class="list-group-item">
                            <div class="input-group">
                                <span class="input-group-addon">Peso:</span>
                                <input class="input-group-item" type="number" value="{{ gado.peso }}" name="peso">
                            </div>
                            <div class="input-group">
                                <span class="input-group-addon">Brinco:</span>
                                <input class="input-group-item" type="number" value="{{ gado.brinco_id }}" pattern="[0-9]+$" name="brinco_id">
                            </div>
                    </li>
                    {% endfor %}
                </ul>
        </div>
    </div>
{% endblock %}

controle_gado/controle_gado/templates/core/login.html
{% extends 'core/base.html' %}

{% block body %}
<div class="jumbotron">
    <div class="container">
        <h1>Insira seus dados:</h1>
        <form class="form-group" action="/login" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="input-group col-lg-6">
                    <span class="input-group-addon">@</span>
                    {{ form.username }}
                </div>
            </div>
            <div class="row">
                <div class="input-group col-lg-6">
                    <span class="input-group-addon">
                        <i class="fa fa-asterisk"></i>
                    </span>
                    {{ form.password }}
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-success">
                <i class="fa fa-user-plus"></i>
                Entrar</button>
        </form>
    </div>
</div>
{% endblock %}